### ISSUE TITLE
[DSC 2 - Write and compile a DSC Configuration]The example should include Example(configuration name) at the end of the configuration example

### ISSUE THREAD

**Issue by Smoovsky** [MicrosoftDocs/PowerShell-Docs-DSC#171]
The example should include ```Example```(configuration name) at the end of the configuration example.

Current:
```
Configuration Example {
    # Import the module that contains the Registry DSC Resource.
    Import-DscResource -ModuleName PSDscResources

    # The Registry DSC Resource can ensure the state of registry keys
    Registry DscTest {
        Key       = 'HKEY_CURRENT_USER\DscTest'
        ValueName = 'Example'
        Ensure    = 'Present'
        ValueData = 'Test Value'
        ValueType = 'String'
    }
}
```

Proposed:
```
Configuration Example {
    # Import the module that contains the Registry DSC Resource.
    Import-DscResource -ModuleName PSDscResources

    # The Registry DSC Resource can ensure the state of registry keys
    Registry DscTest {
        Key       = 'HKEY_CURRENT_USER\DscTest'
        ValueName = 'Example'
        Ensure    = 'Present'
        ValueData = 'Test Value'
        ValueType = 'String'
    }
}

Example
```

Without the configuration name at the end, the configuration won't be compiled when you call the script.

Also I'm not sure if the doc should clarify that you can define multiple configurations in one file and just include names of all configuration at the end and calling the script will result in all configurations to be compiled at once.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b781b0b-299e-8b99-891f-e02716242b53
* Version Independent ID: f1e9736c-9cb5-4e66-ce20-7fb5a59ecd26
* Content: [Write and compile a DSC Configuration - PowerShell](https://learn.microsoft.com/en-us/powershell/dsc/how-tos/configurations/write-and-compile?view=dsc-2.0)
* Content Source: [dsc/docs-conceptual/dsc-2.0/how-tos/configurations/write-and-compile.md](https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/blob/main/dsc/docs-conceptual/dsc-2.0/how-tos/configurations/write-and-compile.md)
* Product: **powershell**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
That information is in the article under the **Compile the configuration** section.
