### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by dh-orko** [MicrosoftDocs/PowerShell-Docs-DSC#207]
### Type of issue

Typo

### Feedback

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/powershell/dsc/overview?view=dsc-2.0

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/blob/main/dsc/docs-conceptual/dsc-2.0/overview.md

### Author

sdwheeler

### Document Id

7befffa4-ef78-f531-1a36-ecce7355978c

**Comment by michaeltlombardi** [comment]
Closing as spam, since the issue contains no details about what or where the typo is.
