### ISSUE TITLE
Installation part is incomplete

### ISSUE THREAD

**Issue by yangxinyun** [MicrosoftDocs/PowerShell-Docs-DSC#244]
### Type of issue

Missing information

### Feedback

The chapter that should have described DSCv3 installation is missing from this page https://learn.microsoft.com/en-us/powershell/dsc/overview?view=dsc-3.0&preserve-view=true

### Page URL

https://learn.microsoft.com/en-us/powershell/dsc/overview?view=dsc-3.0&preserve-view=true

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/blob/main/dsc/docs-conceptual/dsc-3.0/overview.md

### Author

@sdwheeler

### Document Id

7befffa4-ef78-f531-1a36-ecce7355978c

**Comment by sdwheeler** [comment]
@michaeltlombardi
![image](https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/assets/19415881/acc89f9a-ecd0-4e1f-bbff-d7030ea10c8b)
