### ISSUE TITLE
Import-DscResource -Module  or -ModuleName ?

### ISSUE THREAD

**Issue by HarikrishnanKM** [MicrosoftDocs/PowerShell-Docs-DSC#251]
### Type of issue

Typo

### Feedback

In 1.1 document for composite resources 
https://learn.microsoft.com/en-us/powershell/dsc/resources/authoringresourcecomposite?view=dsc-1.1
Should be 
 `Import-DscResource -Module `  or  `Import-DscResource -ModuleName` ?
 
![Error-Dsc](https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/assets/50079202/2c366f28-e185-4425-89c1-695f0a3c2b91)

when we try writing it is giving below options only 
![Correct-DSC](https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/assets/50079202/fcd2e370-2f57-4bcb-8e22-515b8562093b)

### Page URL

https://learn.microsoft.com/en-us/powershell/dsc/resources/authoringresourcecomposite?view=dsc-1.1

### Content source URL

https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/blob/main/dsc/docs-conceptual/dsc-1.1/resources/authoringResourceComposite.md

### Author

@sdwheeler

### Document Id

3b881d76-ee94-94bd-4719-440c698d8856

**Comment by sdwheeler** [comment]
It should be module name.

**Comment by HarikrishnanKM** [comment]
Thanks , hope it is corrected in this document.
https://learn.microsoft.com/en-us/powershell/dsc/resources/authoringresourcecomposite?view=dsc-1.1
Could see, there are 3 entries with -Module instead of -ModuleName in this page.

**Comment by sdwheeler** [comment]
See the linked PR #252
