### ISSUE TITLE
Windows Server 2022

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/PowerShell-Docs-DSC#29]
Should the article be updated to add this OS?

According to https://docs.microsoft.com/en-us/windows-server/get-started/editions-comparison-windows-server-2022, DSC seems to be supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702922ad-7b71-6dd0-37ee-9efad626ad9f
* Version Independent ID: 60157828-986c-43e3-a151-9ed69ebdddd7
* Content: [Get started with Desired State Configuration (DSC) for Windows - PowerShell](https://docs.microsoft.com/en-us/powershell/dsc/getting-started/wingettingstarted?view=dsc-1.1)
* Content Source: [dsc/docs-conceptual/dsc-1.1/getting-started/winGettingStarted.md](https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/blob/main/dsc/docs-conceptual/dsc-1.1/getting-started/winGettingStarted.md)
* Product: **powershell**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by sdwheeler** [comment]
Closed by #35
