### ISSUE TITLE
Problem with Code

### ISSUE THREAD

**Issue by sip03ds** [MicrosoftDocs/PowerShell-Docs-DSC#43]
Hi, 

I have tested the code provided using:
- Powershell 7.2.1
- PSDscResources 2.12.0.0

and I get errors that PSDscResources\WindowsFeature is not recognized. 

When I try with:
- Powershell 5.1 
- PSDscResources 2.12.0.0

the code is compiled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8b94a1d-6e83-0149-4bd4-f726ce2120f1
* Version Independent ID: 132e701b-85f0-a012-86ce-b735d64976e3
* Content: [DSC Configurations - PowerShell](https://docs.microsoft.com/en-us/powershell/dsc/concepts/configurations?view=dsc-3.0)
* Content Source: [dsc/docs-conceptual/dsc-3.0/concepts/configurations.md](https://github.com/MicrosoftDocs/PowerShell-Docs-DSC/blob/main/dsc/docs-conceptual/dsc-3.0/concepts/configurations.md)
* Product: **powershell**
* GitHub Login: @sdwheeler
* Microsoft Alias: **sewhee**

**Comment by mgreenegit** [comment]
Thank you for reporting this. In looking at the issue, we have identified a bug that will require a new release of the PSDesiredStateConfiguration module. We are triaging the work and will try to get the fix out soon.

**Comment by FreefallGeek** [comment]
![powershellWindowsFeatureError](https://user-images.githubusercontent.com/3144507/159510041-ece33e64-2b3e-4d3f-9af3-b37e6064e48c.png)
Experiencing the same.

Is there currently a work-around for this? The original comment indicated that w/ Powershell 5.1 the PSDSC module handles the WindowsFeature resource correctly, but when I attempt to use Powershell 5.1 to run PSDesiredStateConfiguration I get the following:
The module 'C:\Program Files\WindowsPowerShell\Modules\PSDesiredStateConfiguration\3.0.0\PSDesiredStateConfiguration.psd1' requires a minimum Windows PowerShell version of '7.2' to run.

**Comment by sdwheeler** [comment]
PSDesiredStateConfigurationV2.0.5 assume the path separator as ":".
- Linux has path separator as ":"
- Windows has path separator as ";"

We are working on a fix. This is not a docs issue. Closing this docs issue.
