### ISSUE TITLE
Needs a space in the document

### ISSUE THREAD

**Issue by thomaskennedy1066** [MicrosoftDocs/PowerShell-Docs-DSC#55]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell DSC I am using.

### Version

1.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/dsc/getting-started/winGettingStarted?view=dsc-1.1#apply-the-configuration-to-the-machine

### Description of the documentation error

Configuration documents (MOF files) can be applied to the machineusing the [Start-DscConfiguration](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/start-dscconfiguration) cmdlet.

Should become 

Configuration documents (MOF files) can be applied to the machine using the [Start-DscConfiguration](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/start-dscconfiguration) cmdlet.

### Suggested fix

Configuration documents (MOF files) can be applied to the machineusing the [Start-DscConfiguration](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/start-dscconfiguration) cmdlet.

Should become 

Configuration documents (MOF files) can be applied to the machine using the [Start-DscConfiguration](https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/start-dscconfiguration) cmdlet.

**Comment by michaeltlombardi** [comment]
Thanks for reporting this, @thomaskennedy1066! I'll get this updated today.
