### ISSUE TITLE
Incorrect values of the "Ensure" option

### ISSUE THREAD

**Issue by ds185357** [MicrosoftDocs/PowerShell-Docs-DSC#57]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell DSC I am using.

### Version

1.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/windows/windowsoptionalfeatureresource?view=dsc-1.1

### Description of the documentation error

In the "Syntax" section the "Ensure" option is listed with possible values "Enable" and "Disable", but these values should be "Present" and "Absent"

The same mistake is also on https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/windows/windowsoptionalfeaturesetresource?view=dsc-1.1

This most probably applies to all DSC versions (1.1, 2.0, 3.0)

### Suggested fix

Change the following:
Ensure = [string] { Enable | Disable }
To:
Ensure = [string] { Present | Absent }

**Comment by michaeltlombardi** [comment]
Thanks for taking the time to report this, @ds185357!

Looking at the resource as it is implemented on my machine, for v1.1 it _does_ seem to actually have **Enable**/**Disable** as the valid options for **Ensure**:

![image](https://user-images.githubusercontent.com/14190564/164754195-d5eb356d-71ae-478a-a5cf-e18d7c86a1ac.png)

I think what might be causing some confusion here is that the documentation on this page is for the version of the **WindowsOptionalFeature** DSC Resource as it exists in v1.1. There's a short note to this effect at the top of the document:

> This documentation of this DSC resource covers the version that is included with PowerShell prior to version 7.2. The PSDscResources module contains new and updated that are officially supported by Microsoft. The PSDscResources module is available from the PowerShell Gallery.
>
> For more information and updated documentation, see the [README](https://github.com/PowerShell/PSDscResources/blob/dev/README.md) in the GitHub repository.

The change for **Ensure** to use the **Present**/**Absent** values came later and only applies to those newer versions which are available with the [PSDscResources module](https://github.com/PowerShell/PSDscResources#windowsoptionalfeature).

For now, as the documentation matches the implementation of v1.1 and is noted as only being for v1.1, I'm closing this issue. If you notice anything else or have further concerns, please let me know!
