### ISSUE TITLE
DSC Node won't update resource after changing the resource's checksum

### ISSUE THREAD

**Issue by Luzemin** [MicrosoftDocs/PowerShell-Docs-DSC#83]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell DSC I am using.

### Version

1.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/dsc/pull-server/package-upload-resources?view=dsc-1.1#updating-resources

### Description of the documentation error

> You can force a Node to update its resources by changing the version number in the archive's name, **or by creating a new checksum**. The Pull Client will check for newer versions of required resources, as well as updated checksums, when its LCM refreshes.

1. I try to change the code of the current resource and create a new checksum for the resource, the DSC node **won't** pull the resource.
2. I try to change the version of the resource and create a new checksum for the resource, the DSC node **will** pull the resource.

### Suggested fix

If changing the resource code and creating a new checksum is not working fine, please remove it.
if I am wrong please kindly reply to me and explain why then ignore my suggestion.

**Comment by michaeltlombardi** [comment]
Hi, @Luzemin! Thanks for taking the time to file this issue. The feature is documented to match the implementation.

It seems like you may have encountered a bug or other problem. Unfortunately, we're not able to provide support in this repository.

I would suggest that you try posting your problem in a community support forum with a detailed minimal repro that shows the behavior you're seeing in a lab environment, if possible. That helps folks see what might be wrong more easily.

For a list of community forums see: [the community support resource][support].

[support]: https://docs.microsoft.com/powershell/scripting/community/community-support

**Comment by Luzemin** [comment]
I did a lot of tests and found that if I **only change the resource code then re-create checksum for the resource.zip and do not change the version number**, DSC Node will not update the resource After the first time.

_Although no one will do this, the version number is usually updated when the code is updated_

so I think the document should be updated from 
```
You can force a Node to update its resources by changing the version number in the archive's name, or by creating a new checksum. 
```
to
```
You can force a Node to update its resources by changing the version number in the archive's name and creating a new checksum. 
```
