### ISSUE TITLE
How to test the custom DSC resource with MOF?

### ISSUE THREAD

**Issue by ethanhou99** [MicrosoftDocs/PowerShell-Docs-DSC#88]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell DSC I am using.

### Version

1.1

### Link to affected document

https://docs.microsoft.com/en-us/powershell/dsc/resources/authoringresourcemof?view=dsc-1.1

### Description of the documentation error

Hi there,

I just followed the guide of Writing a custom DSC resource with MOF and it was very clear and helpful. However, I didn't find the description to teach how to test the custom DSC resource with MOF. 

There is a testing description in another document here: https://docs.microsoft.com/en-us/powershell/dsc/resources/authoringresourceclass?view=dsc-1.1, but it didn't helpful.

Could you please provide more information?

Thanks,
Ethan

### Suggested fix

Add more details on how to test the custom DSC resource with MOF.

**Comment by michaeltlombardi** [comment]
Hello, @ethanhou99! Thanks for filing this. There's some information about testing your resources (and other things to check when you're developing them) here in the [Resource authoring checklist][1].

[1]: https://docs.microsoft.com/en-us/powershell/dsc/resources/resourceauthoringchecklist?view=dsc-1.1
